#!/bin/bash
RAILS_ENV=production rake assets:precompile
# rm -rf ../zackexplosion/assets
# mv -vf public/assets/ ../zackexplosion/
# mkdir public/assets

# clean old mani file
rm -rf ../zackexplosion/assets/mani*.json

# copy new assets
cp -av public/* ../zackexplosion/

# remove local compile assets
rm -rf public/assets/*

# get newest manifile
cp -v ../zackexplosion/assets/mani*.json public/assets/

git add .
git commit -m 'update manifest'

cd ../zackexplosion
git branch gh-pages
git add .
git commit -m 'update assets'
git push origin gh-pages

cd ../blog
#pwd
#ls

#git push heroku master
git remote | xargs -L1 git push --all