#!/bin/bash
RAILS_ENV=production rake assets:precompile
rm -rf ../zackexplosion/assets
mv -vf public/assets/ ../zackexplosion/
mkdir public/assets
cp -v ../zackexplosion/assets/mani*.json public/assets/
git add .
git commit -m 'update manifest'

cd ../zackexplosion
git add .
git commit -m 'update assets'
git push origin gh-pages

cd ../blog
#pwd
#ls

git push heroku master
